AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lambda-artifacts-a2fc6d0a966ac021/4d109a4fa86c06553cd9a3e294e0c105
      Handler: example.HandlerIntegerJava17
      Runtime: java17
      Description: Java function
      MemorySize: 2048
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AWSLambdaSQSQueueExecutionRole
      Tracing: Active
      Events:
        SQSQueue:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - SQSQueue
              - Arn
            BatchSize: 10
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyLambdaQueue
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
          - DeadLetterQueue
          - Arn
        maxReceiveCount: 3
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyLambdaDeadLetterQueue
