AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lambda-artifacts-a2fc6d0a966ac021/0194591659838bb7775661ea1abf91f4
      Handler: example.HandlerIntegerJava17
      Runtime: java17
      Description: Java function
      MemorySize: 2048
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
