AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:

  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/java17-examples-1.0-SNAPSHOT.jar
      Handler: example.HandlerIntegerJava17
      Runtime: java17
      Description: Java function
      MemorySize: 2048
      Timeout: 900 #15min
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - Statement:
            - Effect: Allow
              Action: 
                - s3:*
              Resource: 
                - arn:aws:s3:::*
                - arn:aws:s3:::*/*
      Tracing: Active
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)



